# Generated by Django 4.1.2 on 2022-11-14 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_image', models.ImageField(null=True, upload_to='')),
                ('company_name', models.CharField(max_length=300)),
                ('job_description', models.CharField(max_length=5000)),
                ('published_date', models.DateTimeField(auto_now_add=True)),
                ('job_vacancy', models.CharField(max_length=50)),
                ('job_nature', models.CharField(max_length=50)),
                ('job_salary', models.CharField(max_length=50)),
                ('job_location', models.CharField(max_length=500)),
                ('company_detail', models.CharField(max_length=5000)),
                ('qualification_text', models.CharField(max_length=500)),
                ('qualification1', models.CharField(max_length=200)),
                ('qualification2', models.CharField(max_length=200)),
                ('qualification3', models.CharField(max_length=200)),
                ('qualification4', models.CharField(max_length=200)),
            ],
        ),
    ]
