# Generated by Django 4.1.2 on 2022-11-14 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0002_application'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='website',
        ),
    ]
