# Generated by Django 4.1.2 on 2022-11-14 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0004_alter_application_email_alter_application_job_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobs',
            old_name='company_name',
            new_name='job_name',
        ),
    ]
