# Generated by Django 4.1.2 on 2022-11-15 08:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobapp', '0005_rename_company_name_jobs_job_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobs',
            name='job_salary2',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobs',
            name='company_detail',
            field=models.TextField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='job_description',
            field=models.TextField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='qualification_text',
            field=models.TextField(max_length=500),
        ),
    ]
