# Generated by Django 4.1.2 on 2022-11-16 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0006_application_user_jobs_job_salary2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobs',
            name='qualification_text',
        ),
        migrations.AddField(
            model_name='jobs',
            name='responsibility1',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobs',
            name='responsibility2',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobs',
            name='responsibility3',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobs',
            name='responsibility4',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
