# Generated by Django 4.1.2 on 2022-11-18 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0009_myuuidmodel_alter_application_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='OneTimeLinkModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('one_time_code', models.CharField(max_length=20)),
                ('expiry_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
