# Generated by Django 4.1.2 on 2022-11-21 15:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobapp', '0010_onetimelinkmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='job',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='jobapp.jobs'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='application',
            name='letter',
            field=models.CharField(blank=True, default=1, max_length=10000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='application',
            name='name',
            field=models.CharField(blank=True, default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='application',
            name='resume',
            field=models.FileField(blank=True, default=1, upload_to='images'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='application',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
